spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3307/tmdtnhom3"
    username: root
    password: "gungun2k3"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: hopeso2k3@gmail.com
    password: ckwyzqvvblmephdi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
fileUpload:
  rootPath: C:\Users\My Computer\OneDrive\Desktop\TMDT\TMDT-nhom3-frontend\public\images\product

jwt:
  signerKey: "lemmYw3VPItk8KxJQVquC0TG2QSqm6jw0GhQbZ6vm/zXlOmNnzTgLCWS3Xutxvv4"